### ISSUE TITLE
运行 pytest 报错

### ISSUE THREAD

**Issue by matthewxuda** [Leozhanggg/ApiTesting#1]
==================================================================================== ERRORS ====================================================================================
_______________________________________________________ ERROR collecting PyDemo/testcase/perRelated/test_addAudltCard.py _______________________________________________________
ImportError while importing test module '/Users/xianxian/Desktop/work/ApiTesting/PyDemo/testcase/perRelated/test_addAudltCard.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
PyDemo/testcase/perRelated/test_addAudltCard.py:9: in <module>
    from comm.utils.readYaml import read_yaml_data
E   ModuleNotFoundError: No module named 'comm'
_______________________________________________________ ERROR collecting PyDemo/testcase/register/test_addOrUpCurBact.py _______________________________________________________
ImportError while importing test module '/Users/xianxian/Desktop/work/ApiTesting/PyDemo/testcase/register/test_addOrUpCurBact.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
PyDemo/testcase/register/test_addOrUpCurBact.py:9: in <module>
    from comm.utils.readYaml import read_yaml_data
E   ModuleNotFoundError: No module named 'comm'
_________________________________________________________ ERROR collecting PyDemo/testcase/register/test_findParam.py __________________________________________________________
ImportError while importing test module '/Users/xianxian/Desktop/work/ApiTesting/PyDemo/testcase/register/test_findParam.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
PyDemo/testcase/register/test_findParam.py:9: in <module>
    from comm.utils.readYaml import read_yaml_data
E   ModuleNotFoundError: No module named 'comm'
____________________________________________________ ERROR collecting PyDemo/testcase/register/test_getAdultCurbactList.py _____________________________________________________
ImportError while importing test module '/Users/xianxian/Desktop/work/ApiTesting/PyDemo/testcase/register/test_getAdultCurbactList.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
PyDemo/testcase/register/test_getAdultCurbactList.py:9: in <module>
    from comm.utils.readYaml import read_yaml_data
E   ModuleNotFoundError: No module named 'comm'
_______________________________________________________ ERROR collecting PyDemo/testcase/register/test_initCanSelInfo.py _______________________________________________________
ImportError while importing test module '/Users/xianxian/Desktop/work/ApiTesting/PyDemo/testcase/register/test_initCanSelInfo.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
PyDemo/testcase/register/test_initCanSelInfo.py:9: in <module>
    from comm.utils.readYaml import read_yaml_data
E   ModuleNotFoundError: No module named 'comm'
___________________________________________________________________ ERROR collecting config/test_template.py ___________________________________________________________________
ImportError while importing test module '/Users/xianxian/Desktop/work/ApiTesting/config/test_template.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
config/test_template.py:10: in <module>
    from comm.unit.initializePremise import init_premise
comm/unit/initializePremise.py:12: in <module>
    from comm.unit import apiSend, readRelevance, replaceRelevance
comm/unit/apiSend.py:10: in <module>
    from comm.unit import apiMethod
comm/unit/apiMethod.py:12: in <module>
    from requests_toolbelt import MultipartEncoder
E   ModuleNotFoundError: No module named 'requests_toolbelt'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 6 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=============================================================================== 6 error in 0.57s ====================

**Comment by matthewxuda** [comment]
<img width="1440" alt="屏幕快照 2021-10-19 19 31 48" src="https://user-images.githubusercontent.com/5927005/137901364-c61d493e-bf57-4861-9f72-e599b1d9e38e.png">
报错了

**Comment by Leozhanggg** [comment]
你用的是哪个版本？貌似是之前的bug，把test_template.py后缀替换错了，所以找不到，可以更新一下代码
